### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by zqpvr** [daechir/xenos-install-kit#1] opened 2022-06-08 12:41 UTC
there is no password for sda2 but what do I put for volume I tried sda3 I'm confused

**Comment by daechir** [comment] 2022-06-11 01:06
Hi,

If you're okay with the predefined defaults and you've verified that they match your system setup then all you need to change are the variables where the $ is present. This would be luks_password, username and userpass, If you're not okay with the predefined defaults, say you want to use another timezone, then you should edit that as-well. Also note that when selecting a luks_password you should avoid using spaces as this can cause quirky behavior (Its been awhile since I last tested this). 

As for the volume variable, this is the name of the volume group that resides inside the LUKS LVM on /dev/sda2. You can change this to whatever you like but I'd stay away from using any disk names like sda, sdb, sdc and etc.

**Comment by daechir** [comment] 2022-06-13 22:03
Hi,

After extensive testing I can verify that the scripts are working as intended and cannot reproduce your issue. I am unsure as to how your issue is occurring and will need further information to diagnose.

1) Are you using the latest Arch iso?
2) Are you installing to a single drive? What kind of drive is it (Vendor and model would be helpful too)?  
3) When you are running the script can you see the password properly echo'd to stdin (Inside the console/terminal)?
4) Can you create a example mock password similar to the one you're using?

**Comment by daechir** [comment] 2022-06-15 01:07
Hi,

Based off of the feedback you've provided it sounds like the scripts are working as intended. However, a fix seems necessary for USB keyboards or non us keymaps. Unfortunately this can become quite complicated since localectl cannot be run while inside chroot (As I had tried to fix prior to [v3g4](https://github.com/daechir/xenos-install-kit/commit/e50474fe2d616df12062acb4fadfdf85d889c7f0)). Without a fix for this it seems that certain modules required for either may be excluded from the initial ramdisk.

Since I have no way to test this on my end you'll have to manually test on yours. Here's a few fixes that you can try:

Fix 1:

In S1.sh setup_drive() add the command loadkeys "${your_keymap}" before timedatectl set-ntp true like so:

```
setup_drive(){
    loadkeys "${your_keymap}" 
 
    # Set the system time
    timedatectl set-ntp true
```
Next in enter_chroot() add this command after locale generation to ensure the keymap is persistent:

```
enter_chroot(){ 
  ...
  echo "LANG=${language}" > /etc/locale.conf

  echo "KEYMAP=${your_keymap}" > /etc/vconsole.conf
```

Remember to replace ${your_keymap} with the name of the keymap.

Fix 2:

Should fix 1 not work then you'll most likely have to add the drive/module for your keyboard to MODULES=() in /etc/mkinitcpio.conf. When booted into the Arch iso you can run "lsusb" to find the device name and driver/module. If that doesn't output the associated driver/module try "lsusb –v" or "lsusb –t".

Then in S1.sh enter_chroot() add this command:

```
enter_chroot(){ 
  ...
  sed -i "s/^MODULES=.*/MODULES=(${your_keymap_module})/g" /etc/mkinitcpio.conf
  sed -i "s/^HOOKS=.*/HOOKS=(base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck)/g" /etc/mkinitcpio.conf
```
Again replace ${your_keymap_module} with the name of the module.

Let me know which fix works for you.

**Comment by daechir** [comment] 2022-06-15 04:49
Hi,

Please refrain from closing issues that aren't solved in the future.

**Comment by daechir** [comment] 2022-06-15 04:49
Summarizing this issue:
The luks_password variable was stripping out uppercase and special characters due to the use of double quotes.

Solution:
See commit [v3g5 ](https://github.com/daechir/xenos-install-kit/commit/950609370d46ce35bd592034059b90662829af61).

Verified by:
Testing and comparing variable output in the shell.

**Closed by daechir** 2022-06-15 04:49 UTC
Labels: documentation, good first issue

**Comment by daechir** [comment] 2022-06-15 16:30
Per [comment](https://github.com/daechir/xenos-install-kit/issues/1#issuecomment-1155865461)

Summarizing the issue:
Without a defined keymap certain keyboard modules may be excluded from the initial ramdisk.

Solution:
See commit [v3g6](https://github.com/daechir/xenos-install-kit/commit/b5f1ff7a18cd0bb32d1653498345dfd65ee58be1)

Verified by:
Testing inside the live iso.
